In [4]:
import pandas as pd
import numpy as np
import os
import torch

In [5]:
stocks = pd.read_pickle('data/stock_code.pkl')
stocks = stocks['stock'].values
for stock in stocks:
    if os.path.exists('data/' + str(stock) + '.pkl') == False:
        break
    data = pd.read_pickle('data/' + str(stock) + '.pkl')
    data = data[~data.isnull().any(axis=1)]
    data[['open_rate', 'close_rate', 'low_rate', 'high_rate', 'avg']] = data[['open', 'close', 'low', 'high', 'avg']].sub(data['pre_close'], axis=0).div(data['pre_close'], axis=0)
    data = data[['open_rate', 'close_rate', 'low_rate', 'factor', 'high_rate', 'avg', 'close']]
    data.to_pickle('part_data/' + str(stock) + '.pkl')

In [ ]:
stocks = pd.read_pickle('data/stock_code.pkl')
stocks = stocks['stock'].values
for stock in stocks:
    if os.path.exists('data/' + str(stock) + '.pkl') == False:
        break

In [12]:
stocks = pd.read_pickle('data/stock_code.pkl')
stocks = stocks['stock'].values
for stock in stocks:
    if os.path.exists('pred/' + str(stock) + '.pkl') == False:
        continue
    data = pd.read_pickle('pred/' + str(stock) + '.pkl')
    if np.isnan(data).any():
        print(stock)
        break

In [7]:
data = pd.read_pickle('train/' + '000018.XSHE.pkl')

In [8]:
data

array([[[nan, nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan, nan],
        ...,
        [nan, nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan, nan]],

       [[nan, nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan, nan],
        ...,
        [nan, nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan, nan]],

       [[nan, nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan, nan],
        ...,
        [nan, nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan, nan]],

       ...,

       [[nan, nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan, nan],
        ...,
        [nan, nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan, nan],
        [

In [42]:
tmp = [[1, 2, 3], [2, 3, 4]]
tmp[:2]

[[1, 2, 3], [2, 3, 4]]

In [38]:
data

array([[ 4.19496604e-03,  5.39352777e-03, -1.21853775e-02, ...,
         8.19017179e-03, -3.39592489e-03,  5.03300000e+01],
       [-5.76197099e-03, -1.68885357e-02, -3.11941188e-02, ...,
        -5.76197099e-03, -2.18557520e-02,  4.94800000e+01],
       [-7.67987065e-03,  1.21261116e-03, -2.06143897e-02, ...,
         8.69037995e-03, -5.45675020e-03,  4.95400000e+01],
       ...,
       [-6.03545832e-03,  1.35797812e-02, -1.49000377e-02, ...,
         4.28140324e-02,  1.26367409e-02,  5.37400000e+01],
       [-1.48864905e-03,  1.19091924e-02, -2.97729810e-03, ...,
         4.35429847e-02,  1.97245999e-02,  5.43800000e+01],
       [-1.47112909e-03, -1.83891136e-04, -3.25487312e-02, ...,
         1.47112909e-02, -7.35564546e-03,  5.43700000e+01]])

In [27]:
x = []
x.append(data[:60][:6])
x

[array([[ 4.19496604e-03,  5.39352777e-03, -1.21853775e-02,
          6.82960679e-01,  8.19017179e-03, -3.39592489e-03,
          5.03300000e+01],
        [-5.76197099e-03, -1.68885357e-02, -3.11941188e-02,
          6.82960679e-01, -5.76197099e-03, -2.18557520e-02,
          4.94800000e+01],
        [-7.67987065e-03,  1.21261116e-03, -2.06143897e-02,
          6.82960679e-01,  8.69037995e-03, -5.45675020e-03,
          4.95400000e+01],
        [-4.23899879e-03, -3.49212757e-02, -3.49212757e-02,
          6.82960679e-01, -4.03714170e-03, -2.34154219e-02,
          4.78100000e+01],
        [-5.85651537e-03,  6.90232169e-03, -1.40138046e-02,
          6.82960679e-01,  1.98703200e-02,  6.90232169e-03,
          4.81400000e+01],
        [ 4.36227669e-03,  1.86954715e-03, -9.97091816e-03,
          6.82960679e-01,  1.43331948e-02,  3.94682177e-03,
          4.82300000e+01]])]

In [28]:
x.append(data[:60][:6])

In [37]:
x[0]

array([[ 4.19496604e-03,  5.39352777e-03, -1.21853775e-02,
         6.82960679e-01,  8.19017179e-03, -3.39592489e-03,
         5.03300000e+01],
       [-5.76197099e-03, -1.68885357e-02, -3.11941188e-02,
         6.82960679e-01, -5.76197099e-03, -2.18557520e-02,
         4.94800000e+01],
       [-7.67987065e-03,  1.21261116e-03, -2.06143897e-02,
         6.82960679e-01,  8.69037995e-03, -5.45675020e-03,
         4.95400000e+01],
       [-4.23899879e-03, -3.49212757e-02, -3.49212757e-02,
         6.82960679e-01, -4.03714170e-03, -2.34154219e-02,
         4.78100000e+01],
       [-5.85651537e-03,  6.90232169e-03, -1.40138046e-02,
         6.82960679e-01,  1.98703200e-02,  6.90232169e-03,
         4.81400000e+01],
       [ 4.36227669e-03,  1.86954715e-03, -9.97091816e-03,
         6.82960679e-01,  1.43331948e-02,  3.94682177e-03,
         4.82300000e+01]])

In [49]:
test = pd.read_pickle('train/000001.XSHE.pkl')
test.shape

array([[[-0.00337838, -0.0045045 , -0.01013513,  0.9133562 ,
          0.00112613, -0.00563063],
        [-0.00339367, -0.00226244, -0.010181  ,  0.9133562 ,
          0.        , -0.00452489],
        [ 0.00113379, -0.00226757, -0.00453515,  0.9133562 ,
          0.00226757, -0.00226757],
        [-0.00227273, -0.01590909, -0.01704546,  0.9133562 ,
         -0.00113636, -0.01022727],
        [-0.00461894,  0.00230947, -0.00808314,  0.9133562 ,
          0.00923788,  0.        ],
        [-0.00115207, -0.00691244, -0.01267281,  0.9133562 ,
         -0.00115207, -0.00691244],
        [-0.00348028, -0.01508121, -0.01508121,  0.9133562 ,
          0.00116009, -0.00580046],
        [-0.00824499,  0.00588928, -0.01766784,  0.9133562 ,
          0.00942285, -0.00824499],
        [-0.00468384,  0.00702576, -0.0058548 ,  0.9133562 ,
          0.01639344,  0.00702576],
        [-0.00348837, -0.02674419, -0.02790698,  0.9133562 ,
         -0.00232558, -0.01860465],
        [ 0.00477897, -0.00119

In [68]:
test2 = pd.read_pickle('train/000002.XSHE.pkl')
test3 = pd.read_pickle('train/000004.XSHE.pkl')
x = []
x_pred = []
x.append(test2[:-1])
x.append(test3[:-1])
x_pred.append([test2[-1]])
x_pred.append([test3[-1]])
x = np.concatenate(x, axis=0)
x_pred = np.concatenate(x_pred, axis=0)

In [69]:
x.shape

(362, 60, 6)

In [70]:
x_pred.shape

(2, 60, 6)

In [51]:
test.shape

(182, 60, 6)

In [54]:
tmp = test[-1]
tmp.shape


(60, 6)

In [77]:
test4 = pd.read_pickle('pred/000002.XSHE.pkl')
test5 = pd.read_pickle('pred/000004.XSHE.pkl')
y = []
y_pred = []
y.append(test4[:-1])
y.append(test5[:-1])
y_pred.append([test4[-1]])
y_pred.append([test5[-1]])
y = np.concatenate(y, axis=0)
y_pred = np.concatenate(y_pred, axis=0)

In [63]:
test4.shape

(182, 65)

In [78]:
y.shape

(362, 65)

In [80]:
from torch import Tensor
y = Tensor(y)

In [85]:
input_y = y[:, :60]
input_y

tensor([[11.4400, 11.4000, 11.1800,  ...,  9.9300, 10.0400,  9.8900],
        [11.4000, 11.1800, 10.7900,  ..., 10.0400,  9.8900,  9.4300],
        [11.1800, 10.7900, 10.8500,  ...,  9.8900,  9.4300,  9.4800],
        ...,
        [11.5300, 11.6800, 11.8000,  ..., 18.1600, 17.1800, 17.7900],
        [11.6800, 11.8000, 11.6200,  ..., 17.1800, 17.7900, 17.5700],
        [11.8000, 11.6200, 11.5500,  ..., 17.7900, 17.5700, 17.8400]])

In [83]:
expected_y = y[:, -60:]
expected_y

tensor([[10.9000, 10.7800, 10.6300,  ...,  9.3300,  9.2100,  9.1800],
        [10.7800, 10.6300, 11.0100,  ...,  9.2100,  9.1800,  9.4600],
        [10.6300, 11.0100, 10.6400,  ...,  9.1800,  9.4600, 10.0000],
        ...,
        [12.0300, 11.6100, 12.2500,  ..., 17.8900, 18.1500, 18.3600],
        [11.6100, 12.2500, 12.0800,  ..., 18.1500, 18.3600, 19.1400],
        [12.2500, 12.0800, 11.9500,  ..., 18.3600, 19.1400, 18.2900]])

In [88]:
input_y[5]

tensor([10.9000, 10.7800, 10.6300, 11.0100, 10.6400, 10.5000, 10.6400, 10.5400,
        10.3800, 10.2600, 10.4200, 10.3800, 10.3000, 10.1700, 10.1700, 10.5200,
        10.4600, 10.1500, 10.1300,  9.9300,  9.9900,  9.8200,  9.8800,  9.7400,
         9.7600,  9.7000,  9.7100,  9.6100,  9.3400,  9.4000,  9.4100,  9.0500,
         9.1800,  9.4100,  9.9600, 10.2000, 10.0600,  9.7900,  9.6000,  9.4400,
         9.4900,  9.1800,  9.5100,  9.5200, 10.0600,  9.8400,  9.9000, 10.2100,
        10.1500, 10.2000,  9.9800, 10.0600,  9.9300, 10.0400,  9.8900,  9.4300,
         9.4800,  9.3300,  9.2100,  9.1800])

In [89]:
expected_y[0]

tensor([10.9000, 10.7800, 10.6300, 11.0100, 10.6400, 10.5000, 10.6400, 10.5400,
        10.3800, 10.2600, 10.4200, 10.3800, 10.3000, 10.1700, 10.1700, 10.5200,
        10.4600, 10.1500, 10.1300,  9.9300,  9.9900,  9.8200,  9.8800,  9.7400,
         9.7600,  9.7000,  9.7100,  9.6100,  9.3400,  9.4000,  9.4100,  9.0500,
         9.1800,  9.4100,  9.9600, 10.2000, 10.0600,  9.7900,  9.6000,  9.4400,
         9.4900,  9.1800,  9.5100,  9.5200, 10.0600,  9.8400,  9.9000, 10.2100,
        10.1500, 10.2000,  9.9800, 10.0600,  9.9300, 10.0400,  9.8900,  9.4300,
         9.4800,  9.3300,  9.2100,  9.1800])

In [87]:
if (input_y[5] == expected_y[0]).all().sum():
    print(1)

1


In [84]:
expected_y.shape

torch.Size([362, 60])

In [79]:
y_pred.shape

(2, 65)

In [3]:
if torch.cuda.is_available():
    print('ok')

ok
